import type { MonsterTemplate } from "../domain/types";

export const monsterTemplates: MonsterTemplate[] = [
  {
    id: "ember-imp",
    name: "余烬小鬼",
    species: "Imp",
    rarity: "common",
    tags: ["fire", "combat", "crafting"],
    baseStats: {
      maxHealth: 56,
      attack: 15,
      defense: 8,
      speed: 13,
    },
    growthCurveId: "balanced",
    skillPool: ["Spark Jab", "Ash Burst"],
    traitPool: ["Hot Hands", "Overtime"],
    laborProfile: {
      farming: 2,
      crafting: 4,
      store: 1,
    },
    allowedMapIds: ["verdant-border", "glass-cavern"],
    captureRate: 0.46,
    visuals: {
      emoji: "🔥",
      accent: "#d76735",
    },
  },
  {
    id: "moss-boar",
    name: "苔牙猪",
    species: "Boar",
    rarity: "common",
    tags: ["earth", "tank", "idle"],
    baseStats: {
      maxHealth: 78,
      attack: 12,
      defense: 13,
      speed: 8,
    },
    growthCurveId: "durable",
    skillPool: ["Root Rush", "Guard Snort"],
    traitPool: ["Bulky Hide", "Forager"],
    laborProfile: {
      farming: 5,
      crafting: 1,
      store: 2,
    },
    allowedMapIds: ["verdant-border"],
    captureRate: 0.38,
    visuals: {
      emoji: "🐗",
      accent: "#74925a",
    },
  },
  {
    id: "lantern-sprite",
    name: "提灯妖",
    species: "Sprite",
    rarity: "uncommon",
    tags: ["light", "support", "crafting"],
    baseStats: {
      maxHealth: 46,
      attack: 11,
      defense: 7,
      speed: 18,
    },
    growthCurveId: "swift",
    skillPool: ["Guiding Flash", "Quick Mend"],
    traitPool: ["Night Shift", "Bright Focus"],
    laborProfile: {
      farming: 2,
      crafting: 6,
      store: 3,
    },
    allowedMapIds: ["verdant-border", "glass-cavern"],
    captureRate: 0.27,
    visuals: {
      emoji: "🏮",
      accent: "#e1b647",
    },
  },
  {
    id: "basalt-golem",
    name: "玄武岩傀儡",
    species: "Golem",
    rarity: "rare",
    tags: ["stone", "tank", "store"],
    baseStats: {
      maxHealth: 102,
      attack: 17,
      defense: 18,
      speed: 6,
    },
    growthCurveId: "heavy",
    skillPool: ["Crag Slam", "Anchor Stand"],
    traitPool: ["Steady Ledger", "Stone Skin"],
    laborProfile: {
      farming: 3,
      crafting: 2,
      store: 7,
    },
    allowedMapIds: ["glass-cavern"],
    captureRate: 0.19,
    visuals: {
      emoji: "🪨",
      accent: "#7a756a",
    },
  },
  {
    id: "mist-eel",
    name: "雾鳗",
    species: "Eel",
    rarity: "uncommon",
    tags: ["water", "speed", "store"],
    baseStats: {
      maxHealth: 58,
      attack: 14,
      defense: 9,
      speed: 16,
    },
    growthCurveId: "nimble",
    skillPool: ["Slip Strike", "Ripple Wake"],
    traitPool: ["Smooth Seller", "Wet Trail"],
    laborProfile: {
      farming: 3,
      crafting: 3,
      store: 5,
    },
    allowedMapIds: ["glass-cavern"],
    captureRate: 0.31,
    visuals: {
      emoji: "🌫️",
      accent: "#6ba5bd",
    },
  },
];
